sudo: required
dist: trusty
language: node_js
node_js:
  - '6.4'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run init
  - npm install
  - ng build

script: npm test

notifications:
  email: false
  slack:
    rooms:
      secure: oCafEbgWsLHVv2SzhfbrOX+42Tqmck2kl8r/kIARWx4Vy/KN+JAJF+WyQvbpqQNai0wKyEElYdDz4pC9vxzTWnkxcE/jwgLvMwXATpDsMrG34fO+5nTe2IDzEeTBKbe5RLpiped0pc/1hr/luj+Wix+za/7SE6CfFHIkkAOAKprEVBuiG/U80OLR/aNUQ6L2md6Cy+uSb20eQ4XmCmBRrj2F5BOStjQVNR+UDAPhaXTsGwrssPofktaNmgRUdMvL0MU8SaOEWdGHEhEqY2mBbRJ6JwqaSZ3Dv/86kEKHYopAVxNmi4b/x7/0UWVPJ98VaNkOQQ8KjiREg+z+aASOSukLo2QwJ5fA12hWfoOI7xZDCOxTnIO/t5ZOOlIAywacaZ/MV+F2KeOOQOSnHs+0eFOeLpOc0FksePAbWfn2ubzr64U3LBn0mIb8huxbd6294dKV7HnXsJK5JdNHcpgIPD6CVfE3g78LpT+V2rGPZ4yh6xDosShWEJUVypmknA4HcsU6bRyHe2uNioLFRpSfA3/wtjlTwsvJZbu6tlW3R/QJHOXFGi5DYxsfCSGGLtKqfloDWnJGE4eLcBP9RQnhlnkjQfW/HAfjmT8btKw57fQkoaPWNjMFcAdSYRbCquDYD0a0wYb+WWVdI1B+QSwTFqsdjTLW5YT03Bs/0r5zjKM=
    on_failure: always
    on_start: always
    on_success: always
