# https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories/
version: "{build}"
shallow_clone: true

# branches to build
branches:
  # branches are not built because master is only updated via pull requests and a pull request can only be merged when the test passes 
  only:
    - master

services:
  - iis
  
install:
  - ps: Install-Product node stable
  - cmd: npm run appveyor:install

build_script:
  - npm run appveyor:build

test_script:
  - npm run appveyor:test

artifacts:
  - path: dist

notifications:
  - provider: Slack
    incoming_webhook: 
      secure: UTeDEvUM8lGmOLUwIt/BzYrxGGjPwVDxSo0kKhrHkBIuO5vOJgFBKOR10ggLGN1BhfcubNFlftrDUB8inzVeblH9oCDsZK7hqjXQmn/BszA=  
    channel: croquet-australia
    on_build_success: true
    on_build_failure: true
    template: |
      Build <{{buildUrl}}|{{buildVersion}}> *{{status}}*.
      
      _{{commitMessage}}_ (<{{commitUrl}}|{{commitId}}>) for {{projectName}}@{{branch}} by {{commitAuthor}}.
